/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class initViewUI extends Laya.View {
		public txt:Laya.Label;
        public static  uiView:any ={"type":"View","props":{"width":750,"height":1334},"compId":2,"child":[{"type":"Label","props":{"y":642,"x":225,"width":300,"var":"txt","text":"0%","height":50,"fontSize":36,"color":"#000000","bold":true,"align":"center"},"compId":3}],"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(initViewUI.uiView);
        }
    }
    REG("ui.initViewUI",initViewUI);
    export class mainuiUI extends Laya.View {
		public shezhi:Laya.Image;
		public xuanguan:Laya.Image;
		public shuaxin:Laya.Sprite;
		public kuaijin:Laya.Sprite;
		public jinyaoshi:Laya.Image;
		public yaoshishu:laya.display.Text;
		public dengjishuzi:Laya.FontClip;
        public static  uiView:any ={"type":"View","props":{"width":750,"height":1334},"compId":2,"child":[{"type":"Image","props":{"y":25,"x":559,"width":171,"skin":"pubRes/qiandi.png","sizeGrid":"0,44,0,42","height":78},"compId":10},{"type":"Image","props":{"y":29,"x":30,"width":75,"var":"shezhi","skin":"pubRes/ic_setting_1.png","height":73},"compId":3},{"type":"Image","props":{"y":31,"x":149,"width":67,"var":"xuanguan","skin":"pubRes/ic_list_1.png","height":71},"compId":5},{"type":"Sprite","props":{"y":34,"x":268,"width":64,"var":"shuaxin","texture":"pubRes/ic_reset_1.png","height":64},"compId":6},{"type":"Sprite","props":{"y":34,"x":383,"width":70,"var":"kuaijin","texture":"pubRes/ic_skip_1.png","height":59},"compId":7},{"type":"Image","props":{"y":27,"x":572,"width":82,"var":"jinyaoshi","skin":"pubRes/ic_key_1.png","height":80},"compId":8},{"type":"Text","props":{"y":36,"x":653,"width":65,"var":"yaoshishu","text":"2","height":60,"fontSize":60,"runtime":"laya.display.Text"},"compId":11},{"type":"Sprite","props":{"y":157,"x":300,"texture":"pubRes/dengji.png"},"compId":12},{"type":"FontClip","props":{"y":159,"x":401,"var":"dengjishuzi","value":"1","skin":"pubRes/shuzi.png","sheet":"01234 56789"},"compId":17}],"loadList":["pubRes/qiandi.png","pubRes/ic_setting_1.png","pubRes/ic_list_1.png","pubRes/ic_reset_1.png","pubRes/ic_skip_1.png","pubRes/ic_key_1.png","pubRes/dengji.png","pubRes/shuzi.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(mainuiUI.uiView);
        }
    }
    REG("ui.mainuiUI",mainuiUI);
    export class mainViewUI extends Laya.View {
        public static  uiView:any ={"type":"View","props":{"width":750,"height":1334},"compId":2,"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(mainViewUI.uiView);
        }
    }
    REG("ui.mainViewUI",mainViewUI);
}